### ISSUE TITLE
codec can't decode byte 0xa5 in position 0

### ISSUE THREAD

**Issue by the1killer** [legoduded/palworld-worldoptions#7]
Did the 1.3.0 update break this? I was just trying to see what was in my personal worldsettings.sav file to compare with server's

```
python main.py C:\Users\XXXXX\AppData\Local\Pal\Saved\SaveGames\######\#########\WorldOption.sav

Found uesave
Found settings
Traceback (most recent call last):
  File "C:\Users\XXXXX\Downloads\palworld-worldoptions-master\palworld-worldoptions-master\src\main.py", line 80, in <module>
    main()
  File "C:\Users\XXXXX\Downloads\palworld-worldoptions-master\palworld-worldoptions-master\src\main.py", line 76, in main
    convert_to_worldoptions(args.uesave, args.settings_file, args.output)
  File "C:\Users\XXXXX\Downloads\palworld-worldoptions-master\palworld-worldoptions-master\src\main.py", line 48, in convert_to_worldoptions
    config_settings_json = create_palworldsettings(settings_file)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\Downloads\palworld-worldoptions-master\palworld-worldoptions-master\src\lib\palworldsettings.py", line 191, in create_palworldsettings
    raw_config = load_palworldsettings(path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\Downloads\palworld-worldoptions-master\palworld-worldoptions-master\src\lib\palworldsettings.py", line 179, in load_palworldsettings
    for line in f:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 0: invalid start byte
Looks like you encountered a critcal error
Check your settings and open a bug report if the issue persists
Press RETURN to close
```

**Comment by legoduded** [comment]
If you're looking to decompress your WorldOption.sav file check out https://github.com/cheahjs/palworld-save-tools

This tool is for migrating a dedicated server PalWorldSettings.ini to WorldOption.sav
